name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^4.0.3
  firebase_messaging: ^15.0.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
<<<<<<< Updated upstream
=======
  local_auth: ^2.2.0
  logger: ^2.3.0
>>>>>>> Stashed changes
  sqflite: ^2.3.3
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
